logger:
  format: "text"
  log_level: "debug"

database:
  database_url: "host=localhost port=5432 user=tg_crypter password=tg_crypter dbname=tg_crypter sslmode=disable"

telegram_bot:
  bot_token: ""

api_server:
  bind_addr: ":8080"
  schema_route: "/"
